# Cargo config file
# Specifies configuration for all `cargo ...` commands


# Environment variables
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG='rust_web_app=debug'

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path
SERVICE_WEB_FOLDER="web-folder/"
